name: Snake Game

on:
  schedule:
    - cron: "0 */24 * * *" # Atualiza a cada 24h
  workflow_dispatch:       # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: CodeByCarlos2k01
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=00ffff&color_dots=#161b22,#4c749e,#00ffff,#8f2864
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=00ffff&color_dots=#0d1117,#4c749e,#00ffff,#8f2864

      - name: Publicar na branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
