name: Snake Game

on:
  schedule:
    - cron: "0 0 * * *"   # 1x por dia (00:00 UTC)
  workflow_dispatch:

permissions:
  contents: write          # permite publicar na branch 'output'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Gerar animação
        uses: Platane/snk@v3
        with:
          github_user_name: CodeByCarlos2k01
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
          # Personalização opcional:
          # color_snake: "00ffff"
          # color_dots: "#0d1117,#4c749e,#00ffff,#8f2864"

      - name: Publicar na branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
            target_branch: output
            build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
